### ISSUE TITLE
Different pseudo characters

### ISSUE THREAD

**Issue by rightaway** [1stdibs/icu-pseudo-translate#1]
Would you be open to considering different choices for pseudo characters, or allowing for the choice of pseudo characters to be passed in as configuration? For example, some of the characters are a bit less readable.

For example I think these characters

```
ś, ţ, ɏ, ď
```

are more readable than

```
ƨ, ƭ, ¥, δ
```

If you agree I can provide a full list of characters that could be more readable. I can provide them for both upper and lower case characters.

Or would you be able to offer a way to pass in a string, such as `pseudoTranslate.chars('AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxWyZz')` (these would be the new pseudo characters)?

**Comment by rightaway** [comment]
Here are some options

```js
{
  A: 'ÀÁÂÃÄÅĀĂĄǺȀȂ',
  a: 'àáâãäåāăąǻȁȃ',
  B: 'ßƁɃʙ',
  b: 'ƀƂƃƄƅɓ',
  C: 'ĆĈĊČ',
  c: 'ćĉċč',
  D: 'ĎĐƉƊ',
  d: 'ďđ',
  E: 'ĒĔĖĘĚȄȆ',
  e: 'ēĕėęěȅȇ',
  F: 'Ƒ',
  f: 'ƒ',
  G: 'ĜĞĠĢ',
  g: 'ĝğġģ',
  H: 'ĤĦ',
  h: 'ĥħ',
  I: 'ĨĪĬĮİ',
  i: 'ĩīĭįı',
  J: 'ĵ',
  j: 'Ĵ',
  K: 'ĶƘ',
  k: 'ķĸƙ',
  L: 'ĹĻĽĿŁ',
  l: 'ĺļľŀł',
  M: 'Ṁ',
  m: 'мɱṁ',
  N: 'ŃŅŇŊƝ',
  n: 'ńņňŉŋƞ',
  O: 'ŌŎŐƠ',
  o: 'ōŏőơ',
  P: 'Ƥ',
  p: 'ƥƿ',
  Q: 'ǪǬ',
  q: 'ǫǭɋ',
  R: 'ŔŖŘƦ',
  r: 'ŕŗř',
  S: 'ŚŜŞŠ',
  s: 'śŝşš',
  T: 'ŢŤŦ',
  t: 'ţťŧ',
  U: 'ŨŪŬŮŰŲ',
  u: 'ũūŭůűų',
  V: 'ѴѶ',
  v: 'ѵѷ',
  W: 'Ŵ',
  w: 'ŵ',
  X: 'Ж',
  x: 'ж',
  Y: 'ŶŸƳȲɎ',
  y: 'ŷƴȳɏ',
  Z: 'ŹŻŽƵ',
  z: 'źżžƶ',
}
```

**Comment by twhid** [comment]
Hi @rightaway -- something with my settings on github didn't alert me to these messages. 

I'm open to a PR where one can provide their own map, sure.

**Comment by twhid** [comment]
Closing this, feel free to open a PR.
